/// Flutter icons RejosariPutraIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RejosariPutraIcon
///      fonts:
///       - asset: fonts/RejosariPutraIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class RejosariPutraIcons {
  RejosariPutraIcons._();

  static const _kFontFam = 'RejosariPutraIcon';
  static const String? _kFontPkg = null;

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowDown = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowUp = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contacts = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxArrowLeft = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxArrowRight = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronDown = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronLeft = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronRight = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevronUp = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dismiss = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData documentEdit = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData documentPrint = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeOff = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moreVertical = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigation = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoppingBag = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subtract = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
